# Generated by Django 3.0.6 on 2020-05-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management_app', '0002_auto_20200510_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeetasks',
            name='status',
            field=models.CharField(choices=[('0', 'New'), ('1', 'In Progress'), ('2', 'Completed')], default='0', max_length=1, verbose_name='Task Status'),
        ),
    ]
